spring.datasource.url=jdbc:mysql://localhost:3306/portfolio?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.cors.allowed-origins=http://localhost:5173,https://portfolio-roger-malabanan.vercel.app

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true

resend.api-key=${RESEND_API_KEY}
resend.from-email=onboarding@resend.dev
# CHANGE TO YOUR OWN DOMAIN
app.notification-email=${OWNER_EMAIL}