spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.cors.allowed-origins=${FRONTEND_URL}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true

server.port=${PORT:8080}

resend.api-key=${RESEND_API_KEY}
# CHANGE TO YOUR OWN DOMAIN
resend.from-email=onboarding@resend.dev
app.notification-email=${OWNER_EMAIL}