spring.application.name=backend

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui.html

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}